# Generated by Django 3.2.11 on 2022-01-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notifications",
            field=models.ManyToManyField(to="core.Notification_list"),
        ),
    ]
