# Generated by Django 3.2.11 on 2022-01-31 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_notification_notifications"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notification_List",
            new_name="NotificationList",
        ),
    ]
