# Generated by Django 3.2.11 on 2022-02-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220207_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notifications',
            field=models.ManyToManyField(to='core.NotificationList'),
        ),
    ]
