# Generated by Django 3.2.11 on 2022-02-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_notification_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='core.NotificationList'),
        ),
    ]
